
const nigeriaState = [
  { name: "Abia State", code: "AB" },
  { name: "Adamawa State", code: "AD" },
  { name: "Akwa Ibom State", code: "AK" },
  { name: "Anambra State", code: "AN" },
  { name: "Bauchi State", code: "BA" },
  { name: "Bayelsa State", code: "BY" },
  { name: "Benue State", code: "BE" },
  { name: "Borno State", code: "BO" },
  { name: "Cross River State", code: "CR" },
  { name: "Delta State", code: "DE" },
  { name: "Ebonyi State", code: "EB" },
  { name: "Edo State", code: "ED" },
  { name: "Ekiti State", code: "EK" },
  { name: "Enugu State", code: "EN" },
  { name: "Federal Capital Territory", code: "FC" },
  { name: "Gombe State", code: "GO" },
  { name: "Imo State", code: "IM" },
  { name: "Jigawa State", code: "JI" },
  { name: "Kaduna State", code: "KD" },
  { name: "Kano State", code: "KN" },
  { name: "Katsina State", code: "KT" },
  { name: "Kebbi State", code: "KE" },
  { name: "Kogi State", code: "KO" },
  { name: "Kwara State", code: "KW" },
  { name: "Lagos", code: "LA" },
  { name: "Nasarawa State", code: "NA" },
  { name: "Niger State", code: "NI" },
  { name: "Ogun State", code: "OG" },
  { name: "Ondo State", code: "ON" },
  { name: "Osun State", code: "OS" },
  { name: "Oyo State", code: "OY" },
  { name: "Plateau State", code: "PL" },
  { name: "Sokoto State", code: "SO" },
  { name: "Taraba State", code: "TA" },
  { name: "Yobe State", code: "YO" },
  { name: "Zamfara State", code: "ZA" },
];

const americaState = [
  { name: "Alabama", code: "AL" },
  { name: "Alaska", code: "AK" },
  { name: "American Samoa", code: "AS" },
  { name: "Arizona", code: "AZ" },
  { name: "Arkansas", code: "AR" },
  { name: "Baker Island", code: "UM-81" },
  { name: "California", code: "CA" },
  { name: "Colorado", code: "CO" },
  { name: "Connecticut", code: "CT" },
  { name: "Delaware", code: "DE" },
  { name: "District of Columbia", code: "DC" },
  { name: "Florida", code: "FL" },
  { name: "Georgia", code: "GA" },
  { name: "Guam", code: "GU" },
  { name: "Hawaii", code: "HI" },
  { name: "Howland Island", code: "UM-84" },
  { name: "Idaho", code: "ID" },
  { name: "Illinois", code: "IL" },
  { name: "Indiana", code: "IN" },
  { name: "Iowa", code: "IA" },
  { name: "Jarvis Island", code: "UM-86" },
  { name: "Johnston Atoll", code: "UM-67" },
  { name: "Kansas", code: "KS" },
  { name: "Kentucky", code: "KY" },
  { name: "Kingman Reef", code: "UM-89" },
  { name: "Louisiana", code: "LA" },
  { name: "Maine", code: "ME" },
  { name: "Maryland", code: "MD" },
  { name: "Massachusetts", code: "MA" },
  { name: "Michigan", code: "MI" },
  { name: "Midway Atoll", code: "UM-71" },
  { name: "Minnesota", code: "MN" },
  { name: "Mississippi", code: "MS" },
  { name: "Missouri", code: "MO" },
  { name: "Montana", code: "MT" },
  { name: "Navassa Island", code: "UM-76" },
  { name: "Nebraska", code: "NE" },
  { name: "Nevada", code: "NV" },
  { name: "New Hampshire", code: "NH" },
  { name: "New Jersey", code: "NJ" },
  { name: "New Mexico", code: "NM" },
  { name: "New York", code: "NY" },
  { name: "North Carolina", code: "NC" },
  { name: "North Dakota", code: "ND" },
  { name: "Northern Mariana Islands", code: "MP" },
  { name: "Ohio", code: "OH" },
  { name: "Oklahoma", code: "OK" },
  { name: "Oregon", code: "OR" },
  { name: "Palmyra Atoll", code: "UM-95" },
  { name: "Pennsylvania", code: "PA" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Rhode Island", code: "RI" },
  { name: "South Carolina", code: "SC" },
  { name: "South Dakota", code: "SD" },
  { name: "Tennessee", code: "TN" },
  { name: "Texas", code: "TX" },
  { name: "United States Minor Outlying Islands", code: "UM" },
  { name: "United States Virgin Islands", code: "VI" },
  { name: "Utah", code: "UT" },
  { name: "Vermont", code: "VT" },
  { name: "Virginia", code: "VA" },
  { name: "Wake Island", code: "UM-79" },
  { name: "Washington", code: "WA" },
  { name: "West Virginia", code: "WV" },
  { name: "Wisconsin", code: "WI" },
  { name: "Wyoming", code: "WY" },
];

const allState = [nigeriaState,americaState]

export default allState;
